### ISSUE TITLE
Please clarify the function of the following commands

### ISSUE THREAD

**Issue by E3V3A** [kou1okada/apt-cyg#31]
@kou1okada 

There are a number of commands which is not at all clear what they are doing or what their purpose is.
They are: 

```bash
completion-install # to install completion (of what??)
packages-total-size [PATTERN_OF_SECTION]
show-packages-busyness PACKAGE_NAMES
get-proxy
```

I have no idea what you mean here: [Busyness](https://www.merriam-webster.com/dictionary/busyness) of what??

**Comment by E3V3A** [comment]
* What do you mean with packages (plural) total size? 
* What do you mean with  PATTERN_OF_SECTION? 

If you show some examples of those, and the output, I may be able to help you reword its function into something that make more sense. 

* What do you mean with `completion-install`? (That does not make any sense, grammatically.) What is getting complete (or completetd?) here? I contrary to what?

**Comment by kou1okada** [comment]
`packages-total-size` sub command calculate the total size of currently cygwin provided from setup.ini file.
This can estimate the required disk size for full mirrored cygwin package repository.
Does "packages-total-size" sounds little strange?
This means `total-size` sub sub command under the the `packages` sub command.
Perhaps, this should be separated to `apt-cyg packages total-size`.

PATTERN_OF_SECTION restricts category of packages which is calculated total-size.
You can find section names with `describe` sub command.
For example, `apt-cyg packages-total-size dev` calculates total size of packages which belong the dev section.

**Comment by E3V3A** [comment]
Aha! :)

> Perhaps, this should be separated to apt-cyg packages total-size

Yeah, that sound better, unless you wanna do: `size-of-all-packages`? 

> You can find section names with describe sub command.

So what sections are available? I'm not sure this is correct , since for `python3-devel` it is shown as **`Python Interpreters`** which is way too long...

But you still have not said what that `busyness` and `completion-install` is all about? 

Anyway, thank you so much for paying attention and trying to help. 
:1st_place_medal:

**Comment by kou1okada** [comment]
## Better name for `packages-total-size`
Maybe `size-of-all-package` is so nice, but I wanted to be grouping functions with `packages`, when I implemented it.
So, there are `total-count`, `total-size`, `cached-count` and `cached-size` sub sub commands under the `packages` sub command.

## Categories which available
Now, I added `ls-categories` sub command at d9ae7d8e091f6b4034151f9630c67d587173b81a.

Another way, that you can find list of all categories at Select Packages dialog of setup-*.exe as below steps:
1. Open `setup-*.exe`.
2. Click next, next, ... and next while Select Packages dialog displayed.
3. Select `Category` with pull down menu of `View`.

Then, you will see the dialog as below:
![image](https://user-images.githubusercontent.com/1631846/48744207-a237e380-eca9-11e8-9d52-9ac75035d8fb.png)

`Python` is one of a category, `Interpreters` is another one.
You can find them at above list of categories.

## Busyness means about
Windows processes, which is under running, lock files which they are using.
For example, when you are running bash process, /bin/bash.exe,
/usr/bin/cygwin1.dll, /usr/bin/cygreadline7.dll, /usr/bin/cygiconv-2.dll, /usr/bin/cygintl-8.dll and /usr/bin/cygncursesw-10.dll will be locked.
 So, these file can not modify or remove until they will be unlocked.
These state calls as `busy`.
Maybe, `packages show-busy-state` is better than `show-packages-busyness`.

This command was implemented for safe behaviors to upgrade and remove packages.
But currently, it is not used in any sub commands, because it takes too  long time to check busy state for many files.

## The function of `completion-install`
Do you know `bash-completion`?
`completion-install` sub command is a pair of `completion-uninstall` sub command.
`completion-install` installs `/etc/bash_completion.d/apt-cyg` which is script of programmable completion for `apt-cyg`, and `completion-uninstall` uninstall it.

You can use it below steps:
1. Install `bash-completion` with `apt-cyg install bash-completion`.
2. Install `/etc/bash_completion.d/apt-cyg` with `apt-cyg completion-install`.
3. Restart `bash`.

Now, with this, you become to use command line completion for `apt-cyg`.
For example, try to type `apt-cyg get[TAB]` and command line will be automatically complemented to `apt-cyg get-proxy`!

Happy hacking!
But perhaps, it is not so quick under the HDD environment. 😢

**Comment by E3V3A** [comment]
Great Work! :)

* I really like `ls-categories`.  
* As for the `busyness`, that clarifies somewhat. So basically you are checking if there are any lock files for a certain package? (How do you check this?)
* As for `bash-completion`, I know it very well, but my imagination could not stretch that far to see that is what you meant. Great! Why not call it `install-bash-completion` or `install-cmd-completion`?

PS. All what you just said is very useful and helpful. Please consider putting this on your README and cleanup/remove all that other old warnings etc.

**Comment by E3V3A** [comment]
Aha! You're using Perl! 
```perl
# Usage: isbusy [file ...]
function isbusy ()
{
  perl -e 'foreach $i(@ARGV){if(-f $i){open(DATAFILE,"+<",$i)||exit(0);close(DATAFILE);}}exit(1);' -- "$@"
}
```

**Comment by kou1okada** [comment]
I tried to rewrite it with Programming Language C and OpenMP.
But unfortunately I couldn't get any distinct advantages of the performance.
