### ISSUE TITLE
Consider making pip and native setup package for easy install

### ISSUE THREAD

**Issue by E3V3A** [kou1okada/apt-cyg#36]
Perhaps totally overkill, but it would be cools to have this script wrapped up into a package to increase visibility and popularity.

We could warp it up in 2 different places.
1. As a native Cygwin setup package (seem a bit ugly though)
2. As a Python pip package! :+1:  (Yes, you'd need python already installed, but I think most already has this.)

**Comment by kou1okada** [comment]
For plan 1:
I think that it's tough to become me [a cygwin package contributor](https://cygwin.com/packaging-contributors-guide.html).
Because I do not have any connections to cygwin developers.

For plan 2:
I cheer up you if you want to rewrite `apt-cyg` with python.
But I do not have any plans to do it on my fork.

**Comment by kou1okada** [comment]
Use [git](https://github.com/kou1okada/apt-cyg/blob/master/README.md#upgrade-apt-cyg).
I strongly recommend it.
