### ISSUE TITLE
No warning given if mirror is unofficial

### ISSUE THREAD

**Issue by cslycord** [kou1okada/apt-cyg#40]
Currently, apt-cyg is set up on my computer to use ftp://ftp.kr.freebsd.org/pub/cygwin.com/cygwin for its mirror.

Upon running dist-upgrade, the installer warned me that the above mirror is not an official one. It used to be an official one, but recently has been removed from the list and looks like its setup files haven't been updated for several days (where the official mirrors have stuff updated yesterday).

IMO, it would be a good idea to check if the mirror is a current official one and give a warning otherwise.

Thanks.

**Comment by cslycord** [comment]
To clarify, the cygwin-setup executable provided the warning, but apt-cyg doesn't and if installing a package or searching for packages through apt-cyg, it would continue using the old/unofficial mirror without any notice to the user.

**Comment by kou1okada** [comment]
I tried as below:
```
apt-cyg setup -- -B -s ftp://ftp.kr.freebsd.org/pub/cygwin.com/cygwin/
```
But, my the latest `setup-x86_64.exe` version 2.895 did not show such a warning before `Review and confirm changes` dialog.
Where the dialog that you saw such a warning.

By the way, how can we determine the mirror is offical or unofficial?
Do you have any good ideas to determine it?
I have no good ideas to resolve it without cheking `https://cygwin.com/mirrors.lst`.

But, I regard that the GNU PG signature for `setup.ini` is enough to certificate safety any mirrors, as long as cygwin keeps the confidenciarity of the GNU PG secret key
That safty is perfectly equal for official and unofficial mirrors.
We can detect any tampers by checking SHA512 hashes for each package which are containing in `setup.ini` protected by the GNU PG signature.

All most forks of `apt-cyg` check SHA512 hash, but unfortunately all most they do not support verification by the GNU PG except this fork, maybe. :-(

I don't have any concerns for security about using unofficial mirrors, because my fork verifies the GNU PG signature.
Thus I think that is not important to check the mirror is official.

But I saw `setup-x86_64.exe` warning that `setup.ini` on `http://ftp.kr.freebsd.org/pub/cygwin.com/cygwin/` is old as below:
```
This setup.ini is older than the one you used last time you installed cygwin.  Proceed anyway?
```
Hmm, the freshness of contents on unofficial mirrors may be concerned.

**Comment by cslycord** [comment]
1) When I got the warning, I hadn't actually used apt-cyg. I downloaded the
x86 setup.exe upstream and ran it. That's when it tried using the previous
mirror (the same one I'd set apt-cyg to use) and got the warning that it
wasn't official.

2) It may be that the program doesn't give the setup exe doesn't give a
warning when you set the mirror manually like apt-cyg does

3) apt-cyg already has an option for displaying official mirrors. So, it
could be changed to check if the current one is in that list.

I wasn't suggesting that there were security concerns, by the way.

**Comment by kou1okada** [comment]
Hmm, It difficult me to see such a warning.

`apt-cyg mirrors-list` just referes mirrors in `setup.rc` which is made by `setup-x86{,_64}.exe`.
See [here](https://github.com/kou1okada/apt-cyg/blob/be081f2d5f6f25ab9e136bd766b4e20d6f6b6a6e/apt-cyg#L991-L997).
Maybe the latest mirrors-list is https://cygwin.com/mirrors.lst.

**Comment by cslycord** [comment]
The mirror in question doesn't appear in the output of "apt-cyg
mirrors-list" either. It's no longer an official mirror. It was in the past
and if you google the site, you'll see it showing up in google results for
the mirror list site at https://cygwin.com/mirrors.html itself, the site no
longer appears.

But oddly enough, I'm no longer seeing the warning message from
setup-x86.exe

Still, I think it would be a good addition to check if the chosen mirror is
official.

**Comment by cslycord** [comment]
Err... I mean that you'll see the site show up inside the google preview
but when you go to the mirrors.html link, you'll not find that mirror in
the list

**Comment by kou1okada** [comment]
I checked [the Wayback Machike at the Internet Archive](https://web.archive.org/web/*/https://cygwin.com/mirrors.html).
At least it seems that it existed until [2018-12-26](https://web.archive.org/web/20181226124321/https://cygwin.com/mirrors.html).
But, at least, it disappears in [2019-02-18](https://web.archive.org/web/20190218050514/https://cygwin.com/mirrors.html).

**Comment by kou1okada** [comment]
Oops, it came back at [2019-02-20](https://web.archive.org/web/20190220041208/https://cygwin.com/mirrors.html).
