### ISSUE TITLE
Very Hard to Install and not working, getting error

### ISSUE THREAD

**Issue by alexpandain** [kou1okada/apt-cyg#81]
![image](https://user-images.githubusercontent.com/73612338/127782487-21602a9d-f1d2-4cc7-9b2d-29ba55bbe6d8.png)

I could install https://github.com/transcode-open/apt-cyg smoothly and also it works fine but getting error with https://github.com/kou1okada/apt-cyg

Reproduce:
get the apt-cyg file 
run `install apt-cyg /bin`
run  `apt-cyg`
![image](https://user-images.githubusercontent.com/73612338/127782487-21602a9d-f1d2-4cc7-9b2d-29ba55bbe6d8.png)
tried `ln -s apt-cyg /usr/local/bin/apt-cyg`
still same error

**Comment by kou1okada** [comment]
It seems that `iconv.exe` is not installed.
Have you read the [Requirements](https://github.com/kou1okada/apt-cyg#requirements) in `README.md`?
Before using my fork, you must install below packages:
* wget
* ca-certificates
* gnupg
* libiconv <- may  be you forget to install it.

Following commands help you to install them.
```
cd /tmp
wget https://cygwin.com/setup-x86_64.exe
chmod +x setup-x86_64.exe
./setup-x86_64 -q -B -P wget,ca-certificates,gnupg,libiconv
```
If you don't want to use batch installation, drop `-q` option for `setup-x86_64.exe`.
And if your environment is 32bit, you must use `setup-x86.exe` instead of `setup-x86_64.exe`.

**Comment by resistancelion** [comment]
> ![image](https://user-images.githubusercontent.com/73612338/127782487-21602a9d-f1d2-4cc7-9b2d-29ba55bbe6d8.png)
> 
> I could install https://github.com/transcode-open/apt-cyg smoothly and also it works fine but getting error with https://github.com/kou1okada/apt-cyg
> 
> Reproduce:
> get the apt-cyg file
> run `install apt-cyg /bin`
> run `apt-cyg`
> ![image](https://user-images.githubusercontent.com/73612338/127782487-21602a9d-f1d2-4cc7-9b2d-29ba55bbe6d8.png)
> tried `ln -s apt-cyg /usr/local/bin/apt-cyg`
> still same error

`
wget https://raw.githubusercontent.com/kou1okada/apt-cyg/master/apt-cyg -o /bin/apt-cyg
chmod +x /bin/apt-cyg
apt-cyg --version
`

**Comment by kou1okada** [comment]
I don't understand what the problem is.
